{{- if .Values.amplitudeApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: amplitude-api-key
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "amplitude-api-key")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.amplitudeApiKey | b64enc }}
{{- end }}
