{{- if .Values.analyticBackendSalt }}
apiVersion: v1
kind: Secret
metadata:
  name: analytic-backend-salt
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "analytic-backend-salt")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.analyticBackendSalt | b64enc }}
{{- end }}
