{{- if .Values.chatApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: chat-api-key
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "chat-api-key")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.chatApiKey | b64enc }}
{{- end }}
