apiVersion: v1
kind: Secret
metadata:
  name: textual-image-pull-secret
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "textual-image-pull-secret")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.dockerConfigAuth }}
type: kubernetes.io/dockerconfigjson