{{- if .Values.keycloakClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-sso-client-secret
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "keycloak-sso-client-secret")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.keycloakClientSecret | b64enc }}
{{- end }}