{{- with ((.Values.llmProvider).openai).apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: llm-provider-openai-api-key
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "llm-provider-openai-api-key")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
type: Opaque
data:
  secret: {{ . | b64enc }}
{{- end }}
{{- with ((.Values.llmProvider).googleAiStudio).apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: llm-provider-google-ai-studio-api-key
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "llm-provider-google-ai-studio-api-key")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
type: Opaque
data:
  secret: {{ . | b64enc }}
{{- end }}
{{- with ((.Values.llmProvider).vertexAi).apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: llm-provider-vertex-ai-api-key
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "llm-provider-vertex-ai-api-key")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
type: Opaque
data:
  secret: {{ . | b64enc }}
{{- end }}
