apiVersion: v1
kind: Service
metadata:
  name: textual-ml
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "textual.allLabels" (list $ (dict "app" "textual-ml")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
spec:
  selector:
    app: textual-ml
  ports:
    - port: 7701
status:
  loadBalancer: {}