apiVersion: v1
kind: Service
metadata:
  name: textual-asr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "textual.allLabels" (list $ (dict "app" "textual-asr")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
spec:
  selector:
    app: textual-asr
  ports:
    - port: 7703
status:
  loadBalancer: {}