apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "textual.allLabels" (list $ (dict "app" "textual-worker")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
  name: textual-worker
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: textual-worker
  ports:
    - port: 8843
status:
  loadBalancer: {}
