apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-ml
  namespace: {{ .Release.Namespace }}
  labels:
    app: solar-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-ml
  strategy:
    type: {{ .Values.deployStrategy | quote | default "Recreate" }}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: solar-ml
    spec:
      containers:
      - securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: var-logs-public
            mountPath: /usr/bin/solar/logs_public
          - name: var-logs
            mountPath: /usr/bin/solar/logs
          - name: vector-configuration
            mountPath: /usr/bin/solar/vector_config
          - name: tmp
            mountPath: /tmp
        env:
        {{- if (.Values.solar_ml).env}}
        {{- range $key, $value := .Values.solar_ml.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
        image: quay.io/tonicai/solar-ml:{{ .Values.solarVersion }}
        imagePullPolicy: Always
        name: solar-ml
        ports:
          - containerPort: 7701
        resources:
          limits:
            memory: "8Gi"
          requests:
            memory: "1Gi"
            ephemeral-storage: "1Gi"
        startupProbe:
          httpGet:
            path: /health
            port: 7701
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 5
      - name: vector
        image: timberio/vector:latest-alpine
        env:
          - name: VECTOR_SELF_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: VECTOR_SELF_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: VECTOR_SELF_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: LOG_COLLECTION_FOLDER
            value: "/usr/bin/solar/logs_public"
        volumeMounts:
          - name: var-logs-public
            mountPath: "/usr/bin/solar/logs_public"
          - name: vector-configuration
            mountPath: "/usr/bin/solar/vector_config"
          - name: vector-working
            mountPath: "/etc/solar/vector_data"
        args:
          - "-w"
          - "--config"
          - "/usr/bin/solar/vector_config/vector.toml"
      restartPolicy: Always
      imagePullSecrets:
        - name: solar-image-pull-secret
      serviceAccountName: {{ template "solar.serviceAccountName" . }}
      volumes:
        - name: var-logs-public
          emptyDir: {}
        - name: var-logs
          emptyDir: {}
        - name: vector-configuration
          emptyDir: {}
        - name: vector-working
          emptyDir: {}
        - name: tmp
          emptyDir: {}
