apiVersion: v1
kind: Secret
metadata:
  name: textual-encryption-secret
  labels:
    {{- include "textual.allLabels" (list $ (dict "secret-type" "textual-encryption-secret")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}  
type: Opaque
data:
  secret: {{ .Values.textualEncryptionSecret | b64enc }}