apiVersion: v1
kind: Service
metadata:
  name: textual-roberta
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "textual.allLabels" (list $ (dict "app" "textual-roberta")) | nindent 4 }}
  annotations:
    {{- include "textual.allAnnotations" (list $) | nindent 4 }}
spec:
  selector:
    app: textual-roberta
  ports:
    - port: 8801
status:
  loadBalancer: {}